Bump to node20 runtime and resolve bug with Http keepAlive settings
redhat-actions/openshift-tools-installer pull request #106
Opened 2024-07-19 17:52 UTC by komish

### Description

- Bumps runtime environment from Node16 to Node20
  - EOL statement: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
  - Force replacement started June 3rd: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

- Updates @actions/http-client to 2.2.1
  - Allows us to work around this bug, present in Node20, that causes delays in runtime https://github.com/nodejs/node/issues/47228
  - Other examples: https://github.com/actions/toolkit/issues/1643
  - PR addressing the issue in http-toolkit: https://github.com/actions/toolkit/pull/1572

- Updates code to support the new version of @actions/http-toolkit

### Related Issue(s)

Fixes #105 

### Checklist

- [ ] This PR includes a documentation change
- [x] This PR does not need a documentation change
---
- [ ] This PR includes test changes
- [x] This PR's changes are already tested
---
- [ ] This change is not user-facing
- [ ] This change is a patch change
- [x] This change is a minor change
- [ ] This change is a major (breaking) change

### Changes made

See above.

2024-07-19 18:02 UTC, acornett21 approved these changes

2024-07-22 11:34 UTC, adambkaplan approved these changes
lgtm

2024-07-22 11:34 UTC, adambkaplan commented
@divyansh42 are you able to approve this?

2024-07-22 12:07 UTC, divyansh42 requested changes

2024-07-22 12:07 UTC, divyansh42 commented on package.json
Could you also please change the node version at https://github.com/redhat-actions/openshift-tools-installer/blob/main/package.json#L24

2024-07-22 15:00 UTC, komish commented on package.json
@divyansh42 Done. 

Note that src/utils/utils.ts:getArch() needed to be updated for this update because `process.arch` now returns a NodeJS.Architecture (previously, just a string).

As such, assigning our internal architecture value `Architectures.AMD64` was throwing a compiler error, so I unioned the types to allow us to assign either of the architecture values there, keeping the rest of the code untouched.

2024-07-22 15:04 UTC, komish commented
Thanks @adambkaplan @divyansh42

2024-07-22 15:04 UTC, komish commented on package.json
If there's a better way to do what I did here, please let me know and I'll send another update.

2024-07-22 15:12 UTC, divyansh42 approved these changes
Thanks for your PR!

2024-07-22 15:12 UTC, divyansh42 commented on package.json
Changes looks good to me.

2024-07-22 15:14 UTC, divyansh42 commented
Could you please try to push some changes again so that it triggers the CI checks.

2024-07-23 14:18 UTC, adambkaplan approved these changes
Updates look good.

2024-07-23 14:32 UTC, merged

2024-07-23 14:44 UTC, divyansh42 commented
The updated action has been released.
Changes should reflect in v1 and v1.13